# Generated by Django 5.2.1 on 2025-05-22 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensess', '0008_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_delete',
            new_name='is_deleted',
        ),
    ]
